<?php

// TABLES
$TABLES = array(
    "USERGROUPROLE_VIEW" => "v_usergrouprole",
    "CLOUD_AUTHPIN_TABLE" => "tblcloud_auth_pin_angular",
    "USER_ACCESS_TABLE" => "tbluser_access",
    "USER_AUTHDETAILS_TABLE" => "tbluser_authdetails",
    "USER_SESSION_TOKEN_TABLE" => "tbluser_session_token",
    "MODULES_TABLE" => "tblmodules",
    "GROUPS_TABLE" => "tblgroups",
    "CLIENTS_TABLE" => "tblclients",
    "PROJECTS_TABLE" => "tblprojects",
    "PROJECT_TEAM_TABLE" => "tblproject_team",
    "ATTENDANCE_TABLE" => "tblattendance",
    "VANDS_SUMMARY_TABLE" => "tblvands_summary",
    "BRANCH_TABLE" => "tblbranch",
    "BRANCH_PRODUCTS_TABLE" => "tblbranch_products",
    "BRANCH_PICKUPSTOCK_PRODUCTS_TABLE" => "tblbranch_pickupstock_products",
    "STOCK_SUMMARY_TABLE" => "tblstock_summary",
    "ROUTE_DETAILS_TABLE" => "tblroute_details",
    "CONSTANTS_TABLE" => "tblconstants",
    "RMD_RETAILER_TABLE" => "tblrmd_retailer",
    "RESPONSE_TABLE" => "tblsurvey_response_details",
    "RESPONSE_DETAILS_TABLE" => "tblsurvey_response_details",
    "MOBILE_SUMMARY_TABLE" => "tblmobile_summary",
    "LEADERBOARD_TABLE" => "tbl_leaderboard",
    "WD_MAPPING_TABLE" => "tblmapping_wd",
    "APP_NOTIFICATION_TABLE" => "tblapp_notification",
    "BREEZE_TEAM_TABLE" => "tblbreeze_team",
    "MDO_ACCESS_TABLE" => "tblmdo_access",
    "ROUTE_DETAILS_BREEZE_TABLE" => "tblroute_details_breeze",
);
