export const basePath = {
  image: 'assets/images/',
  mapMarkers: 'assets/markers/',
  svgIcons: 'assets/icons/',
  url: ''
};

export const baseHref = '';
const baseUrl = `${baseHref}services/`;

export const environment = {
  addClientUrl: baseUrl,
  addGroupUrl: baseUrl,
  addModuleUrl: baseUrl,
  addProjectUrl: baseUrl,
  addTeamUrl: baseUrl,
  addUserUrl: baseUrl,
  apiUrl: baseUrl,
  changePasswordUrl: baseUrl,
  confirmUploadRouteDataUrl: baseUrl,
  deleteDataUrl: baseUrl,
  downloadAttendanceUrl: baseUrl,
  downloadDataUrl: baseUrl,
  downloadExcelUrl: baseUrl,
  editGroupUrl: baseUrl,
  editProductUrl: baseUrl,
  editProfileUrl: baseUrl,
  forgotUrl: baseUrl,
  getActiveUsersUrl: baseUrl,
  getActiveVariantsDataUrl: baseUrl,
  getAddProjectDataUrl: baseUrl,
  // getAnalyticsDataUrl: baseUrl,
  getAttendanceDataUrl: baseUrl,
  getBinderReportDataUrl: baseUrl,
  getCaptchaUrl: baseUrl,
  // getDashboardDataUrl: baseUrl,
  getEvaluationReportDataUrl: baseUrl,
  getGroupDataUrl: baseUrl,
  getListingExcelUrl: baseUrl,
  getLocationsCoveredDataUrl: baseUrl,
  getModuleDataUrl: baseUrl,
  getOutletUniverseDataUrl: baseUrl,
  getProductiveReportDataUrl: baseUrl,
  getRouteDataDownloadDataUrl: baseUrl,
  getRouteDataUploadDataUrl: baseUrl,
  getTeamDataUrl: baseUrl,
  getUobReportDataUrl: baseUrl,
  getUserDataUrl: baseUrl,
  loginUrl: baseUrl,
  logoutUrl: baseUrl,
  noUrlProvidedUrl: baseUrl,
  production: true,
  uploadRouteDataUrl: baseUrl,
  viewAttendanceLocatorUrl: baseUrl,
  viewAttendanceTrackerUrl: baseUrl,
  viewClientsUrl: baseUrl,
  viewBreezeDashboardDataUrl: baseUrl,
  viewDashboardDataUrl: baseUrl,
  viewNpsrDashboardDataUrl: baseUrl,
  viewNpsrDashboard2DataUrl: baseUrl,
  viewProductiveDashboardDataUrl: baseUrl,
  viewSalesDashboardDataUrl: baseUrl,
  aiInsightsUrl: baseUrl,
  viewGroupUrl: baseUrl,
  viewModulesUrl: baseUrl,
  viewProjectsUrl: baseUrl,
  viewTeamsUrl: baseUrl,
  viewUsersUrl: baseUrl,
  viewVanDsDataUrl: baseUrl,
  viewSkuPickupUrl: baseUrl,
  dashboardDataUrl: baseUrl,
};
