<?php

$currentMonthShort = date('M');

$arrSummaryLabels = array(
    "YES" => "Yes",
    "NO" => "No",
    "NA" => "N/A",

    "ATTENDANCE_SUMMARY" => "Attendance Summary",
    "TODAYS_ATTENDANCE" => "Today's Attendance",
    "TODAYS_DAYEND" => "Today's Dayend",
    "TODAYS_LEAVE_WEEKEND" => "Today's Week Off",
    "MTD_ATTENDANCE" => "Total Attendance in $currentMonthShort",
    "LOGIN_TIME" => "Login time",
    "LOGOUT_TIME" => "Logout time",
    "MARKET_WORKING_DAYS" => "Market Working Days",
    "QUALIFIED_MARKET_WORKING_DAYS" => "Qualified Market Working Days",

    "TODAYS_SUMMARY" => "Today's Summary",
    "TOTAL_TIME_SPENT" => "Total Time Spent",
    "OTHER_OUTLET_GROCERY" => "Other Outlet (Grocery)",
    "OTHER_OUTLET_RETAIL" => "Other Outlet (Retail)",
    "OTHER_OUTLET_WHOLESALE" => "Other Outlet (Wholesale)",
    "ROC_SELLIN_SHOPS" => "ROC Sell-in shops",
    "COVERED_TODAY" => "Covered Today",
    "COVERED_MTD" => "Covered MTD",
    "FEEDER_MARKET_SUMMARY" => "Feeder Market Summary",
    "TOTAL_SHOPS" => "Total Shops",
    "ROC_DELIVERY" => "ROC Delivery",
    "OUTLETS_NOT_VISITED_IN_THIS_MONTH" => "Outlets not visited on {ROUTE} in this month",

    "TOTAL_CALLS" => "Total calls",
    "PRODUCTIVE_CALLS" => "Productive calls",
    "NON_PRODUCTIVE_CALLS" => "Non Productive calls",
    "OPENING_STOCK_FILLED" => "Opening Stock Filled",
    "CLOSING_STOCK_FILLED" => "Closing Stock Filled",
    "SALES_DETAILS" => "Sales Details",

    "DAY_SUMMARY" => "Day Summary",
    "TIME_SPENT_IN_MARKET" => "Time Spent In Market",
    "OUTLETS_VISITED" => "Outlets Visited",
    "TOTAL_BILLS_CUT" => "Total Bills Cut",
    "AVG_SALES" => "Avg. Sales (In Ms)",
    "SALES_MONTH_TILL_DATE" => "Sales MTD (In Ms)",
    "FOCUS_SKU_SALES" => "Focus SKU Sales (In Ms)",
    "OUTLET_NOT_DONE_YET" => "Outlet's Not Done Yet",

    "ABSENT_CYCLE_DSS" => "Absent Cycle DSS",
    "COVERED_TOWN_SHOPS" => "Covered Town Shops",
    "COVERED_RURAL_SHOPS" => "Covered Rural Shops",
    "COVERED_VILLAGE_SHOPS" => "Covered Village Shops",
    "PRODUCTIVE_TODAY" => "Productive Today",
    "MONTHLY_SUMMARY" => "Monthly Summary",
    "TOTAL_PLANNED" => "Total Planned",
    "COVERED" => "Covered",
    "PRODUCTIVE" => "Productive",

    "TOTAL_CUSTOMER_CONVERTED" => "Total Customer Converted",
    "PIC_TAKEN_RECEIVING_STOCK" => "Pic Taken (Receiving stock)",
    "PIC_TAKEN_RETURN_STOCK" => "Pic Taken (Return stock)",
    "COMPETITOR_BRAND_DETAILS" => "Competitor Brand Details",

    "TOTAL_CONNECT" => "Total Connect",
    "TOTAL_INTERACTION" => "Total Interaction",
    "TOTAL_CONVERSION" => "Total Conversion",
    "TOTAL_SALES" => "Total Sales",

    "MTD_SUMMARY" => "MTD Summary",
    "TODAYS_SCAN" => "Today's Scan",
    "TOTAL_NEW_GARAGES_VISITED" => "Total New Garages Visited",
    "TOTAL_NEW_APP_INSTALLED" => "Total New App Installed",
    "TOTAL_REPEAT_VISIT" => "Total Repeat Visit",
    "SCAN_MTD" => "Scan MTD",
    "REGISTRATIONS_MTD" => "Registrations MTD",
    "REPEAT_VISIT_MTD" => "Repeat Visit MTD",
    "MECHANIC_MEETS" => "Mechanic Meets",

    "TOTAL_RECCEE" => "Total Reccee",
    "TOTAL_INSTALLATION" => "Total Installation",
    "TOTAL_DIRECT_INSTALLATION" => "Total Direct Installation",

    "TARGET" => "Target",
    "COMPLETED" => "Completed",
    "FIRST_CALL_COMPLETED" => "First Call Completed",
    "SECOND_CALL_COMPLETED" => "Second Call Completed",
    "TOTAL_HOUSE_VISITED" => "Total House Visited",
    "TOTAL_SAMPLED_HOUSE" => "Total Sampled House",
    "OVERALL_SUMMARY" => "Overall Summary",
);
