name: Auto Deploy Angular

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: itcph2
        run: npm install

      - name: Install Composer Dependencies
        working-directory: itcph2
        run: composer install

      - name: Run Lint
        working-directory: itcph2
        run: npm run lint

      - name: Build Angular App
        working-directory: itcph2
        run: npm run build
        continue-on-error: true

      - name: Deploy to Hostinger
        
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./itcph2/dist/browser/
          server-dir: /domains/appilaryradar.com/public_html/

      - name: Send Success Email
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: ✅ Deployment Successful

          to: jainarchi003@gmail.com
          from: GitHub Actions

          body: |
            Your Angular project deployed successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}

            Deployment completed successfully.

      - name: Send Failure Email
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true

          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          subject: ❌ Deployment Failed

          to: jainarchi003@gmail.com
          from: GitHub Actions

          body: |
            Your Angular deployment failed.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}

            Check logs:
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
